name: Build and Push Docker base image

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: build image
        run: |
            docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/nvim-base:latest -f build/docker/Dockerfile.nvim-base .

      - name: push image
        run: |
            docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/nvim-base:latest

